# ===================================================================
# Spring Boot configuration for the "prod" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

logging:
  level:
    ROOT: INFO
    tech.jhipster: INFO
    org.hibernate.SQL: WARN
    com.example.redditclone: INFO

spring:
  devtools:
    restart:
      enabled: false # Disable restart in production
    livereload:
      enabled: false
  jackson:
    serialization:
      indent-output: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://prod-db-host:3306/redditclone
    username: prod-user
    password: prod-pass
  hikari:
    pool-name: Hikari
    auto-commit: false
    maximum-pool-size: 50
    minimum-idle: 10
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate # Ensure the schema is validated but not altered
    properties:
      hibernate:
        ejb:
          interceptor:
            session_scoped: true
  h2:
    console:
      enabled: false
  liquibase:
    enabled: true
    contexts: prod # Only apply changes relevant to production
  mail:
    host: smtp.prod-mail-server.com
    port: 587
    username: prod-mail-user
    password: prod-mail-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: keystore-password
    key-store-type: PKCS12
    key-alias: tomcat

# ===================================================================
# JHipster specific properties
#
# Full reference is available at: https://www.jhipster.tech/common-application-properties/
# ===================================================================

jhipster:
  cache:
    ehcache:
      time-to-live-seconds: 86400 # Set Ehcache TTL to 24 hours
      max-entries: 1000
  cors:
    allowed-origins: 'https://your-domain.com'
    allowed-methods: '*'
    allowed-headers: '*'
    exposed-headers: 'Authorization,Link,X-Total-Count,X-${jhipster.clientApp.name}-alert,X-${jhipster.clientApp.name}-error,X-${jhipster.clientApp.name}-params'
    allow-credentials: true
    max-age: 1800
  security:
    authentication:
      jwt:
        base64-secret: UPDATE_WITH_NEW_BASE64_SECRET_FOR_PROD
        token-validity-in-seconds: 86400
        token-validity-in-seconds-for-remember-me: 2592000
  mail:
    base-url: https://your-domain.com
  logging:
    use-json-format: true
    logstash:
      enabled: true
      host: logstash.prod.your-domain.com
      port: 5000
      ring-buffer-size: 512

# ===================================================================
# Application specific properties
# Add your own application properties here, see the ApplicationProperties class
# to have type-safe configuration, like in the JHipsterProperties above
#
# More documentation is available at:
# https://www.jhipster.tech/common-application-properties/
# ===================================================================

# application:
