package com.example.redditclone.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SubredditAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSubredditAllPropertiesEquals(Subreddit expected, Subreddit actual) {
        assertSubredditAutoGeneratedPropertiesEquals(expected, actual);
        assertSubredditAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSubredditAllUpdatablePropertiesEquals(Subreddit expected, Subreddit actual) {
        assertSubredditUpdatableFieldsEquals(expected, actual);
        assertSubredditUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSubredditAutoGeneratedPropertiesEquals(Subreddit expected, Subreddit actual) {
        assertThat(expected)
            .as("Verify Subreddit auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSubredditUpdatableFieldsEquals(Subreddit expected, Subreddit actual) {
        assertThat(expected)
            .as("Verify Subreddit relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSubredditUpdatableRelationshipsEquals(Subreddit expected, Subreddit actual) {}
}
